# Generated by Django 4.2.7 on 2024-02-24 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_customuser_voted_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("Web Frameworks", "Web Frameworks"),
                            ("Setting up Django", "Setting up Django"),
                            ("URL Mapping", "URL Mapping"),
                        ],
                        max_length=50,
                    ),
                ),
                ("votes", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
