# Generated by Django 4.2.7 on 2024-02-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0005_remove_notes_votes"),
    ]

    operations = [
        migrations.AddField(
            model_name="votes",
            name="votes",
            field=models.BooleanField(default=False),
        ),
    ]
