# Generated by Django 4.2.7 on 2024-02-24 19:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0006_votes_votes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="voted_notes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(), blank=True, default=list, size=None
            ),
        ),
    ]
