# Generated by Django 4.2.7 on 2024-02-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0007_alter_customuser_voted_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="votes",
            name="section",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
